/** Datos de prueba que imitan las respuestas de la API. */

import type {
  ContentIdea,
  CriticismGroup,
  DashboardSummary,
  DataQuality,
  Recommendation,
  RequestItem,
  StrengthItem,
  Topic,
  VideoRow,
} from '@/lib/types';

export const topic: Topic = {
  cluster_key: 'a_humor',
  label_es: 'Humor',
  description_es: 'Comentarios centrados en humor.',
  comment_count: 48,
  unique_video_count: 7,
  positive_count: 40,
  neutral_count: 6,
  negative_count: 2,
  request_count: 3,
  question_count: 1,
  share_of_comments: 0.12,
  mentions_per_1000: 120,
  video_coverage: 0.7,
  recent_share: 0.6,
  previous_share: 0.4,
  trend_score: 0.5,
  trend_direction: 'rising',
  trend_label_es: 'Al alza',
  coverage_score: 0.7,
  confidence_score: 0.82,
  confidence_level: 'alta',
  dominant_video_share: 0.2,
  top_aspects: ['humor'],
  keywords: ['risa', 'gracioso'],
  representative_comments: [
    { text: 'Me río muchísimo con tus vídeos', sentiment: 'positive', likes: 12 },
  ],
  is_noise: false,
  ai_generated_label: false,
};

export const audioTopic: Topic = {
  ...topic,
  cluster_key: 'a_audio',
  label_es: 'Audio',
  comment_count: 14,
  unique_video_count: 4,
  positive_count: 1,
  neutral_count: 3,
  negative_count: 10,
  request_count: 0,
  share_of_comments: 0.04,
  trend_direction: 'falling',
  trend_label_es: 'A la baja',
  confidence_score: 0.55,
  confidence_level: 'media',
  top_aspects: ['audio'],
};

export const viralTopic: Topic = {
  ...topic,
  cluster_key: 'c3',
  label_es: 'Tema de un vídeo viral',
  comment_count: 30,
  unique_video_count: 1,
  dominant_video_share: 0.85,
  confidence_score: 0.3,
  confidence_level: 'baja',
};

export const summary: DashboardSummary = {
  videos_analysed: 12,
  comments_analysed: 400,
  sentiment: {
    positive: 220,
    neutral: 120,
    negative: 40,
    mixed: 15,
    uncertain: 5,
    positive_share: 0.55,
    negative_share: 0.1,
    overall_es: 'positivo',
  },
  questions: 45,
  requests: 30,
  toxic_comments: 6,
  spam_comments: 4,
  top_strength: {
    cluster_key: 'a_humor',
    label_es: 'Humor',
    comment_count: 48,
    unique_video_count: 7,
    positive_count: 40,
    negative_count: 2,
    request_count: 3,
    share_of_comments: 0.12,
    trend_direction: 'rising',
    trend_change: 0.4,
    confidence_level: 'alta',
  },
  top_request: {
    cluster_key: 'a_tutorial',
    label_es: 'Tutoriales',
    comment_count: 22,
    unique_video_count: 5,
    positive_count: 5,
    negative_count: 1,
    request_count: 18,
    share_of_comments: 0.05,
    trend_direction: 'stable',
    trend_change: 0.05,
    confidence_level: 'media',
  },
  top_criticism: {
    cluster_key: 'a_audio',
    label_es: 'Audio',
    comment_count: 14,
    unique_video_count: 4,
    positive_count: 1,
    negative_count: 10,
    request_count: 0,
    share_of_comments: 0.04,
    trend_direction: 'falling',
    trend_change: -0.3,
    confidence_level: 'media',
  },
  fastest_growing: {
    cluster_key: 'a_humor',
    label_es: 'Humor',
    comment_count: 48,
    unique_video_count: 7,
    positive_count: 40,
    negative_count: 2,
    request_count: 3,
    share_of_comments: 0.12,
    trend_direction: 'rising',
    trend_change: 0.4,
    confidence_level: 'alta',
  },
  top_recommendation: {
    title_es: 'Refuerza lo que tu audiencia ya valora: humor',
    category: 'double_down',
    category_label_es: 'Refuerza una fortaleza',
    confidence_level: 'alta',
    priority: 1,
  },
  data_quality_level: 'alta',
  data_quality_score: 0.82,
  primary_warning_es: '1 vídeo(s) tienen los comentarios desactivados y no aportan feedback.',
  intent_counts: { praise: 120, question: 45 },
  median_views: 12_000,
  median_comments_per_1000: 4.2,
  median_likes_per_1000: 38.5,
};

export const recommendation: Recommendation = {
  id: 'rec-1',
  category: 'double_down',
  category_label_es: 'Refuerza una fortaleza',
  title_es: 'Refuerza lo que tu audiencia ya valora: humor',
  explanation_es: '«Humor» aparece de forma positiva en 40 comentarios repartidos por 7 vídeos.',
  reason_es: 'Es el feedback positivo más repetido y aparece en varios vídeos.',
  evidence: {
    supporting_comments: 40,
    supporting_videos: 7,
    total_comments_analysed: 400,
    total_videos_analysed: 12,
    share_of_comments: 0.12,
    mentions_per_1000: 120,
    video_coverage: 0.7,
    trend_direction: 'rising',
    trend_change: 0.4,
    dominant_video_share: 0.2,
    positive_count: 40,
    negative_count: 2,
    request_count: 3,
    question_count: 1,
    performance_association: {},
    representative_comments: [],
    confidence_penalties_es: [],
    source_es: 'Comentarios públicos analizados en esta ejecución.',
  },
  confidence_score: 0.82,
  confidence_level: 'alta',
  priority: 1,
  suggested_format: 'short',
  suggested_format_label_es: 'Short',
  suggested_hook_es: '«Me decís mucho que lo que más os gusta es mi humor…»',
  suggested_experiment_es: 'Publica dos vídeos seguidos que apoyen en el humor.',
  kpi_es: 'Comentarios por cada 1.000 visualizaciones',
  caveat_es: 'Es una asociación estadística, no una garantía de resultados.',
  topic_cluster_key: 'a_humor',
  ai_enriched: false,
};

export const idea: ContentIdea = {
  id: 'idea-1',
  title_es: 'Cómo consigo que mis vídeos hagan reír',
  concept_es: 'Un vídeo centrado en el humor, el aspecto más mencionado por tu audiencia.',
  why_es: 'Encaja con tu audiencia porque «Humor» aparece en 48 comentarios de 7 vídeos.',
  evidence: {
    bullets_es: [
      '48 comentarios mencionan «Humor» (12 % de la muestra analizada).',
      'El tema aparece en 7 de los 12 vídeos analizados.',
    ],
  },
  suggested_format: 'short',
  suggested_format_label_es: 'Short',
  hook_es: '«Me preguntáis muchísimo por mi humor…»',
  call_to_action_es: '«Dime en los comentarios qué quieres que desarrolle.»',
  experiment_es: 'Publica un Short y compara con la mediana del canal.',
  kpi_es: 'Comentarios por cada 1.000 visualizaciones',
  confidence_score: 0.82,
  confidence_level: 'alta',
  overinterpretation_risk_es:
    'El interés observado procede de una muestra de comentarios, no de toda tu audiencia.',
  topic_cluster_key: 'a_humor',
};

export const videos: VideoRow[] = [
  {
    youtube_video_id: 'aaaaaaaaaaa',
    title: 'Vídeo antiguo con buen rendimiento',
    thumbnail_url: null,
    published_at: '2024-01-15T10:00:00Z',
    duration_seconds: 630,
    view_count: 30_000,
    like_count: 1_500,
    comment_count: 200,
    comments_disabled: false,
    likes_per_1000_views: 50,
    comments_per_1000_views: 6.7,
    engagement_actions_per_1000_views: 56.7,
    views_relative_to_median: 2.5,
    performance_band: 'por_encima',
    age_caveat: false,
    age_days: 120,
    analysed_comment_count: 150,
    dominant_topics: [{ cluster_key: 'a_humor', label_es: 'Humor', comment_count: 40 }],
    sentiment_breakdown: { positive: 100, negative: 20 },
    youtube_url: 'https://www.youtube.com/watch?v=aaaaaaaaaaa',
  },
  {
    youtube_video_id: 'bbbbbbbbbbb',
    title: 'Vídeo publicado ayer',
    thumbnail_url: null,
    published_at: '2024-05-30T10:00:00Z',
    duration_seconds: 300,
    view_count: 500,
    like_count: 20,
    comment_count: 5,
    comments_disabled: false,
    likes_per_1000_views: 40,
    comments_per_1000_views: 10,
    engagement_actions_per_1000_views: 50,
    views_relative_to_median: 0.04,
    performance_band: 'reciente',
    age_caveat: true,
    age_days: 1,
    analysed_comment_count: 5,
    dominant_topics: [],
    sentiment_breakdown: {},
    youtube_url: 'https://www.youtube.com/watch?v=bbbbbbbbbbb',
  },
  {
    youtube_video_id: 'ccccccccccc',
    title: 'Vídeo con comentarios desactivados',
    thumbnail_url: null,
    published_at: '2024-03-01T10:00:00Z',
    duration_seconds: 900,
    view_count: 8_000,
    like_count: 300,
    comment_count: null,
    comments_disabled: true,
    likes_per_1000_views: 37.5,
    comments_per_1000_views: null,
    engagement_actions_per_1000_views: 37.5,
    views_relative_to_median: 0.66,
    performance_band: 'por_debajo',
    age_caveat: false,
    age_days: 90,
    analysed_comment_count: 0,
    dominant_topics: [],
    sentiment_breakdown: {},
    youtube_url: 'https://www.youtube.com/watch?v=ccccccccccc',
  },
];

export const requests: RequestItem[] = [
  {
    cluster_key: 'a_tutorial',
    label_es: 'Tutoriales',
    kind: 'tutorial_request',
    kind_label_es: 'Peticiones de tutorial',
    count: 18,
    unique_video_count: 5,
    confidence_level: 'media',
    examples: [{ text: 'Haz un tutorial paso a paso porfa', sentiment: 'neutral', likes: 4 }],
  },
];

export const strengths: StrengthItem[] = [
  {
    aspect: 'humor',
    label_es: 'Humor',
    count: 40,
    unique_video_count: 7,
    share_of_positive: 0.18,
    confidence_level: 'alta',
    examples: [{ text: 'Me río muchísimo', sentiment: 'positive', likes: 12 }],
  },
];

export const criticism: CriticismGroup[] = [
  {
    kind: 'constructive',
    label_es: 'Crítica constructiva',
    description_es: 'Comentarios que señalan un aspecto concreto y mejorable.',
    count: 12,
    items: [
      {
        text: '',
        label_es: 'Audio',
        count: 10,
        unique_video_count: 4,
        actionable: true,
        examples: [{ text: 'No se escucha bien tu voz', sentiment: 'negative', likes: 8 }],
      },
    ],
  },
  {
    kind: 'subjective',
    label_es: 'No gusta (subjetivo)',
    description_es: 'Comentarios negativos sin propuesta concreta de mejora.',
    count: 3,
    items: [{ text: 'No me convence', sentiment: 'negative', likes: 1 }],
  },
  {
    kind: 'harassment',
    label_es: 'Acoso o insultos',
    description_es: 'Comentarios ofensivos detectados automáticamente.',
    count: 2,
    items: [{ text: 'Comentario ofensivo', sentiment: 'negative', likes: 0 }],
  },
  {
    kind: 'spam',
    label_es: 'Posible spam',
    description_es: 'Comentarios que parecen autopromoción.',
    count: 4,
    items: [{ text: 'Visita mi canal', sentiment: 'neutral', likes: 0 }],
  },
];

export const dataQuality: DataQuality = {
  videos_sampled: 12,
  comments_sampled: 450,
  comments_analysed: 400,
  comments_discarded_spam: 20,
  comments_discarded_duplicate: 25,
  comments_discarded_empty: 5,
  videos_with_comments_disabled: 1,
  videos_with_zero_comments: 0,
  videos_missing_views: 0,
  videos_missing_likes: 0,
  sampling_strategy: 'mixed',
  sampling_buckets: { recent: 200, relevant: 200 },
  date_coverage: {
    first: '2024-01-01T00:00:00Z',
    last: '2024-05-30T00:00:00Z',
    span_days: 150,
    missing_dates: 0,
  },
  language_distribution: { es: 320, en: 60, und: 20 },
  dominant_video_share: 0.62,
  viral_view_concentration: 0.55,
  clustering_strategy: 'hdbscan',
  topics_found: 9,
  noise_share: 0.28,
  ai_used: false,
  ai_provider: 'none',
  algorithm_version: '1.0.0',
  embedding_backend: 'hashing',
  sentiment_backend: 'lexicon',
  is_demo: true,
  score: 0.82,
  level: 'alta',
  warnings_es: ['1 vídeo(s) tienen los comentarios desactivados y no aportan feedback.'],
  biases_es: [
    'El 62 % de los comentarios analizados procede de un solo vídeo.',
    'Estos son datos de demostración generados para probar el producto.',
  ],
};
